DB_HOST=localhost
DB_PORT=5432
DB_NAME=mydatabase

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase

spring.datasource.username=myuser
spring.datasource.password=secret

spring.docker.compose.enabled=false